### ISSUE TITLE
uninstall Winget, windows Webpack Error & other errors Jun 2023 build. Error log attached

### ISSUE THREAD

**Issue by fasteddys** [builtbybel/Winpilot#83] opened 2023-08-06 18:37 UTC
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Builtbybel\BloatyNosy\app\bloaty.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Features.Feature.Apps.StoreAppsPrivate.DoFeature()
   at BloatyNosy.MainForm.<>c__DisplayClass21_0.<ApplyFeatures>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at BloatyNosy.MainForm.<ApplyFeatures>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

<img width="761" alt="image" src="https://github.com/builtbybel/BloatyNosy/assets/96149622/9e3b96af-bd63-4026-9a1c-db5a3354fab0">

**Comment by p1xeltw0** [comment] 2023-08-16 05:07
solved a problem??

**Comment by Belim** [comment] 2024-03-19 19:22
The issue is now resolved with the rebranding and successor, [Winpilot](https://github.com/builtbybel/Winpilot/releases).

**Closed by Belim** 2024-03-19 19:22 UTC
